name: Stick Path

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Navigate to folder
      run: cd stick_path
    - name: Lint
      run: cargo clippy -- -Dwarnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
